---
 - name: Install  packages on prod   servers
   hosts: all
   vars:
     custom: pwd
     packages: 
       - vim
       - curl
       - wget
       - git
       - tree
   gather_facts: yes   
   tasks: 
     - name: Install vim, curl, wget, git, tree  
       apt:
         name: "{{ packages }}"
         state: latest
       when: ansible_facts['distribution'] == "Ubuntu"  

     - name: Install vim,curl,wget,git,tree on centos
       yum:
         name: "{{ packages }}"
         state: latest
       when: ansible_facts['distribution'] == "CentOS"

     - name: Run 
       shell:
         cmd: "{{ custom }}"
         