---
 - name: Install vim git curl wget on prod
   hosts: prod
   gather_facts: yes
   tasks: 
     - name: update vim git curl wget on Ubuntu
       when: ansible_facts['distribution'] == "Ubuntu"
       apt:
         name: '*'
         state: latest

     - name: Install vim git curl wget on Ubuntu
       when: ansible_facts['distribution'] == "Ubuntu"
       apt:
         name:
           - vim
           - git
           - curl
           - wget
         state: latest  
         
     - name: Update packages on centos
       when: ansible_facts['distribution'] == "CentOS"
       yum:
         name: '*'
         state: latest

     - name: install vim git curl wget on centos
       when: ansible_facts['distribution'] == "CentOS"
       yum:
         name:
           - vim
           - git
           - curl
           - wget
         state: latest  