---
 - name: Update all packages on dev   servers
   hosts: dev
   vars:
     package: curl
   gather_facts: yes
   tasks: 
     - name: Update all packages on ubuntu
       when: ansible_facts['distribution'] == "Ubuntu"
       apt:
         name: '*'
         state: latest
       
     - name: Update all packages on centos
       when: ansible_facts['distribution'] == "CentOS"       
       yum:
         name: '*'
         state: latest

     - name: Install curl on CentOS
       when: ansible_facts['distribution'] == "CentOS"
       yum:
         name: "{{ package }}"
         state: latest

     - name: Install curl on Ubuntu
       when: ansible_facts['distribution'] == "Ubuntu"
       apt:
         name: "{{ package }}"
         state: latest